"""HTML string templates for the leaderboard."""
from __future__ import annotations

PAGE_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Prism Leaderboard</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; margin: 2em; color: #333; }}
  h1 {{ border-bottom: 2px solid #333; padding-bottom: 0.3em; }}
  h2 {{ color: #555; margin-top: 2em; }}
  table {{ border-collapse: collapse; margin: 1em 0; }}
  th, td {{ border: 1px solid #ddd; padding: 0.5em 0.8em; text-align: right; }}
  th {{ background: #f5f5f5; text-align: left; }}
  td.model {{ text-align: left; font-family: monospace; font-size: 0.9em; }}
  td.score-high {{ background: #d4edda; color: #155724; }}
  td.score-mid  {{ background: #fff3cd; color: #856404; }}
  td.score-low  {{ background: #f8d7da; color: #721c24; }}
  td.empty {{ color: #999; font-style: italic; }}
  .note {{ color: #666; font-size: 0.9em; margin: 0.5em 0 1.5em; }}
</style>
</head>
<body>
<h1>Prism Leaderboard</h1>
<p class="note">Scores are pass@1 (higher is better). Generated by <code>prism leaderboard publish</code>.</p>
{main_section}
{staircase_section}
{sweep_section}
</body>
</html>
"""

EMPTY_STATE = """<p class="note">No benchmark data found — run <code>prism run</code> first.</p>"""

MAIN_HEADER = """<h2>Main Leaderboard</h2>
<table>
<thead><tr><th>Model</th>{benchmark_headers}</tr></thead>
<tbody>
{rows}
</tbody>
</table>
"""

STAIRCASE_HEADER = """<h2>Context Length Staircase</h2>
<p class="note">Performance vs context length for NIAH / RULER MK-NIAH benchmarks.</p>
<table>
<thead><tr><th>Model</th>{length_headers}</tr></thead>
<tbody>
{rows}
</tbody>
</table>
"""

SWEEP_HEADER = """<h2>Reasoning Effort Sweep</h2>
<p class="note">Same base model under different thinking/effort settings.</p>
<table>
<thead><tr><th>Base Model</th><th>Variant</th><th>Effort</th><th>Mean Score</th><th>Total Cost</th></tr></thead>
<tbody>
{rows}
</tbody>
</table>
"""
